### ISSUE TITLE
Issue when enabling zbuffer/depth-culling

### ISSUE THREAD

**Issue by robertsdionne** [gonutz/d3d9#13]
Hello,

I'm not sure if this is an error in d3d9 or in d3dmath or something else, but I have a minimal reproduction here (with C++ working and Golang not working): https://gist.github.com/robertsdionne/9d703b3eb787115556387c2e3bf8fb89

Essentially, I'm drawing a triangle with perspective projection. When using C++ and D3D9 it works when I enable a D24X8 depth-buffer (or D16) and when using Golang with gonutz/d3d9 it does not draw the triangle. I've used the D3DX9 library for matrix transformations in C++ and gonutz/d3dmath in Golang. (You can get the triangle drawing in Golang if you disable the automatic depth buffer in the present-parameters and the render state and remove the zbuffer from the Clear call).

(This is all motivated because I'd like to write a new D3D9 application to use NVIDIA RTX Remix, and I'm most comfortable with Golang, however for some reason the depth buffer is causing issues here.)

Thank you,
Robert

**Comment by robertsdionne** [comment]
Also, this is on Windows 11 with an NVIDIA RTX 3090.

**Comment by gonutz** [comment]
Hey, thanks for the great in-depth issue description. I have to check it out later, but my first guess is that my math library is different, there might be some z problems. I have actually noticed that while writing [this thing](https://ldjam.com/events/ludum-dare/40/minimal-walking-simulator), something might be off. This is just my best guess for now, I will check out your code later :-)

**Comment by robertsdionne** [comment]
It seems like it needs this:
```diff
git diff
diff --git a/device_windows.go b/device_windows.go
index 4043f95..40d372c 100644
--- a/device_windows.go
+++ b/device_windows.go
@@ -1,6 +1,7 @@
 package d3d9

 import (
+       "math"
        "syscall"
        "unsafe"
 )
@@ -868,7 +869,7 @@ func (obj *Device) Clear(
                uintptr(unsafe.Pointer(rectPtr)),
                uintptr(flags),
                uintptr(color),
-               uintptr(z),
+               uintptr(math.Float32bits(z)),
                uintptr(stencil),
                0,
                0,
```

**Comment by robertsdionne** [comment]
Otherwise `1.0` gets cast to `var z uintptr = 1` which is different from `var z uintptr = 0x3f800000`.
See: https://go.dev/play/p/Qdis-zQHmNb

**Comment by robertsdionne** [comment]
I figured this out because I tried replacing `d3dmath` with a `syscall.NewLazyDLL` pointing to `d3dx9.dll` to use the D3DXMath functions, and my floats were getting passed incorrectly also.

**Comment by gonutz** [comment]
Oh, yes you are absolutely right, really nice catch!

Meanwhile I let the programs print their matrices and they are indeed different from one another:

```
Go
===
world
1 0 0 0
0 1 0 0
0 0 1 0
0 0 4 1
view
-1 0  0 0
0  1  0 0
0  0 -1 0
0  0  0 1
proj
2.41    0  0   0
   0 2.41  0   0
   0    0  1   1
   0    0 -0.1 0

C++
===
world
1 0 0 0
0 1 0 0
0 0 1 0
0 0 4 1
view
1 0 0 0
0 1 0 0
0 0 1 0
0 0 0 1
proj
1.81    0    0 0
   0 2.41    0 0
   0    0    1 1
   0    0 -0.1 0
```

**Comment by gonutz** [comment]
I will investigate further later and look at all those float32s that are passed un-chopped and wrongfully converted to uintptrs. Thanks again for this great catch, you made an impactful improvement to this library!

**Comment by gonutz** [comment]
So I changed the translation from `+4` to `-4` in z. Then the example works with the `Float32bits` fix.
For me this means I will overhaul the `d3dmath` once I am done with fixing this library :-)

**Comment by gonutz** [comment]
Alright, `v1.2.2` is out now. I will close this for now, as I said, inverting the z-translation makes your example run.
Now off to fixing `d3dmath`... :-)
Thanks again, this is a major bug that you just fixed. Really great work!

**Comment by gonutz** [comment]
Turns out that `d3dmath` is actually fine, I don't know what happened in my comment above, I must have mixed up some numbers in my code so the C++ and Go versions had different matrices. Also, your gist is one digit off as well, one matrix is (0,1,0) and the other is (0,1,1) but no finger-pointing, please ;-)

I just updated `d3dmath` to include a bit of documentation and will leave it as is, otherwise, for now.
