### ISSUE TITLE
Binding for D3DX

### ISSUE THREAD

**Issue by abdullah2993** [gonutz/d3d9#3]
Will you be adding bindings for D3DX?

**Comment by gonutz** [comment]
Actually I am using my own code for what D3DX does at the moment and have not planned to add bindings to it. D3DX is a layer built on top of the D3D9 API so it is possible to do everything it does yourself.

I have created a simple [d3dmath](https://github.com/gonutz/d3dmath) lib for example. It is not optimized in any way but works for me. The code for LookAt, Perspective and similar functions was actually taken from the msdn online documentation of the respective D3DX functions.

If you would like to add the bindings for D3DX yourself, however, I would be very happy to help you get going. Writing glue code in Go that loads a DLL and wraps the functions is a bit of work but not hard once you know the pattern. You would have to load `D3DX9_43.dll` (or look for a different version on the computer if that is not installed) and then provide the functions and classes you want to expose.

Take a look at [direct3d9_windows.go](https://github.com/gonutz/d3d9/blob/master/direct3d9_windows.go) to get started and hit me up if you encounter any serious problems :-)

**Comment by abdullah2993** [comment]
Thanks for the pointers to get me started on this as I'm only looking to implement the texture related functions so it won't be much work.
Will ask you for help if I get stuck at some point.
Cheers

**Comment by abdullah2993** [comment]
Can you make hResultError an exported type rather then an internal type?

**Comment by abdullah2993** [comment]
I have  made a pull request here: https://github.com/gonutz/d3d9/pull/4

**Comment by gonutz** [comment]
That would be fine but I would like to know if it is really necessary first. Does the D3DX lib use the same error codes. Would you literally have to copy the hResultError code from d3d9 to your project? In that case we can just export it here, that would be an addition to the API, so nothing would break. But I would like to consider it more throughly before doing that.

Once you have something up and running, I will look at your d3dx lib on your github account. How is it going so far?

**Comment by abdullah2993** [comment]
Well although D3DX has it's own [errors](https://msdn.microsoft.com/en-us/library/windows/desktop/bb172825(v=vs.85).aspx) but it does share some general purpose errors with d3d9 but I don't think it is absolutely necessary to export the hResultError the exported Error interface is good enough besides the error constants are already exported. So feel free to close the PR

**Comment by gonutz** [comment]
OK, just copy the implementation for now and if we later see that the code is the same or could benefit from sharing certain parts, we can still do that in the end.
