### ISSUE TITLE
Best way to take a screenshot of a third-party application/game

### ISSUE THREAD

**Issue by ogau** [gonutz/d3d9#5]
Hello! What is the best way to get a screenshot of a third-party application/game in an array of bytes?

**Comment by gonutz** [comment]
Direct3D9 is not your best option for this. It is inteded for rendering. Theoretically you could use the front buffer and copy that but the last time I have done something like that was on DirectX 5, twenty years ago. These days Windows will not give you control over the main graphics front buffer that it uses to render things. You are better off using another library for that. A quick search turned up this library which I just tested on Windows and it works for capturing my desktop window:

https://github.com/vova616/screenshot

There might be problems with capturing a fullscreen game but if you encounter anything like that, please create an issue on the library's repo.

**Comment by ogau** [comment]
Thank you
