### ISSUE TITLE
cannot use flag (type uint32) as type uintptr in argument to procRedrawWindow.Call

### ISSUE THREAD

**Issue by advancedwebdeveloper** [gonutz/d3d9#6]
Hi.
I am trying to build on Windows 10.

> go\src\github.com\gonutz\d3d9\samples\fullscreen>go get -u github.com/AllenDang/gform
> # github.com/AllenDang/w32
> ..\..\..\..\AllenDang\w32\user32.go:1039:10: cannot use flag (type uint32) as type uintptr in argument to procRedrawWindow.Call

> >go env
> set GO111MODULE=
> set GOARCH=amd64
> set GOBIN=
> set GOCACHE=C:\Users\Worker\AppData\Local\go-build
> set GOENV=C:\Users\Worker\AppData\Roaming\go\env
> set GOEXE=.exe
> set GOFLAGS=
> set GOHOSTARCH=amd64
> set GOHOSTOS=windows
> set GOINSECURE=
> set GOMODCACHE=C:\Users\Worker\go\pkg\mod
> set GONOPROXY=
> set GONOSUMDB=
> set GOOS=windows
> set GOPATH=C:\Users\Worker\go
> set GOPRIVATE=
> set GOPROXY=https://proxy.golang.org,direct
> set GOROOT=c:\go
> set GOSUMDB=sum.golang.org
> set GOTMPDIR=
> set GOTOOLDIR=c:\go\pkg\tool\windows_amd64
> set GCCGO=gccgo
> set AR=ar
> set CC=gcc
> set CXX=g++
> set CGO_ENABLED=1
> set GOMOD=
> set CGO_CFLAGS=-g -O2
> set CGO_CPPFLAGS=
> set CGO_CXXFLAGS=-g -O2
> set CGO_FFLAGS=-g -O2
> set CGO_LDFLAGS=-g -O2
> set PKG_CONFIG=pkg-config
> set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\Worker\AppData\Local\Temp\go-build907535614=/tmp/go-build -gno-record-gcc-switches

> >go version
> go version go1.15.2 windows/amd64

**Comment by gonutz** [comment]
I could not reproduce this on my machine, maybe it is a 32 bit issue, I don't know.

Anyway, I just updated the example to use the Windows API directly. This should work everywhere. The problem is that the [gform](https://github.com/AllenDang/gform) library is not mine and I do not have control over it. The build issue you describe is in that library. The other examples, except the `display_info` one, use that library as well. When I get around to it, probably later today or tomorrow, I will replace it with my Win32 wrapper as well.

Until then you probably cannot run those samples either, but keep an eye out for my updates. Also you can try to update the gform library, maybe it is out of date on your machine.

**Comment by advancedwebdeveloper** [comment]
@gonutz , I am on a 64bit machine.

> > Get-ComputerInfo | select WindowsProductName, WindowsVersion, OsHardwareAbstractionLayer
> 
> WindowsProductName WindowsVersion OsHardwareAbstractionLayer
> ------------------ -------------- --------------------------
> Windows 10 Pro     2004           10.0.19041.488

> > Get-WmiObject Win32_Processor
> 
> Caption           : Intel64 Family 6 Model 23 Stepping 10
> DeviceID          : CPU0
> Manufacturer      : GenuineIntel
> MaxClockSpeed     : 2666
> Name              : Intel(R) Core(TM)2 Quad CPU    Q9400  @ 2.66GHz
> SocketDesignation : CPU

> > foreach($gpu in Get-WmiObject Win32_VideoController)
> {
> >   Write-Host $gpu.Description
> > 
> }

> NVIDIA GeForce GT 710

**Comment by advancedwebdeveloper** [comment]
> > Get-ItemProperty "hklm:\Software\Microsoft\DirectX"
> 
>  (default)                 : 1
>  MinFeatureLevel           : 45056
>  MaxFeatureLevel           : 45056
>  D3D12MinFeatureLevel      : 45056
>  D3D12MaxFeatureLevel      : 45056
>  MaxDedicatedVideoMemory   : 2104623104
>  InstalledVersion          : {0, 0, 0, 9...}
>  Version                   : 4.09.00.0904
>  LastUpdaterStartTimestamp : UTC.2020-09-22.19:40:11
>  LastUpdaterStartHresult   : 0
>  PSPath                    : Microsoft.PowerShell.Core\Registry::HKEY_LOCAL_MACHINE\Software\Microsoft\DirectX
>  PSParentPath              : Microsoft.PowerShell.Core\Registry::HKEY_LOCAL_MACHINE\Software\Microsoft
>  PSChildName               : DirectX
>  PSDrive                   : HKLM
>  PSProvider                : Microsoft.PowerShell.Core\Registry
> 
> 

> 
> > $a = Get-ItemProperty "hklm:\Software\Microsoft\DirectX"
> > $strValue = $a.Version
> > switch ($strValue) {
> >>     "4.02.0095"      { $strVersion = "1.0"  }
> >>     "4.03.00.1096"   { $strVersion = "2.0"  }
> >>     "4.04.0068"      { $strVersion = "3.0"  }
> >>     "4.04.0069"      { $strVersion = "3.0"  }
> >>     "4.05.00.0155"   { $strVersion = "5.0"  }
> >>     "4.05.01.1721"   { $strVersion = "5.0"  }
> >>     "4.05.01.1998"   { $strVersion = "5.0"  }
> >>     "4.06.02.0436"   { $strVersion = "6.0"  }
> >>     "4.07.00.0700"   { $strVersion = "7.0"  }
> >>     "4.07.00.0716"   { $strVersion = "7.0a" }
> >>     "4.08.00.0400"   { $strVersion = "8.0"  }
> >>     "4.08.01.0881"   { $strVersion = "8.1"  }
> >>     "4.08.01.0810"   { $strVersion = "8.1"  }
> >>     "4.09.0000.0900" { $strVersion = "9.0"  }
> >>     "4.09.00.0900"   { $strVersion = "9.0"  }
> >>     "4.09.0000.0901" { $strVersion = "9.0a" }
> >>     "4.09.00.0901"   { $strVersion = "9.0a" }
> >>     "4.09.0000.0902" { $strVersion = "9.0b" }
> >>     "4.09.00.0902"   { $strVersion = "9.0b" }
> >>     "4.09.00.0904"   { $strVersion = "9.0c" }
> >>     "4.09.0000.0904" { $strVersion = "9.0c" }
> >>     # NEW LINES
> >>     "6.00.6000.16386" { $strVersion = "10.0" }
> >>     "6.00.6001.18000" { $strVersion = "10.1" }
> >>     "6.01.7600.0000" { $strVersion = "11.0" }
> >>     "6.02.9200" { $strVersion = "11.1" }
> >>     "6.03.9600" { $strVersion = "11.2" }
> >> }
> > $strVersion
> 9.0c

**Comment by gonutz** [comment]
As I said, the problem is probably in the `gform` library that I removed. To be sure, could you pull the latest changes and try to run the fullscreen example again and tell me if it works for you now?

**Comment by gonutz** [comment]
Have you tried the updated example, yet? I do not want to be pushy, I am just eager to find out if I can go ahead and change the other samples to this as well :-)

**Comment by advancedwebdeveloper** [comment]
You may close this issue: I was able to launch an app, which lad to rendering in a full-screen (pink colored).
My cursor was moving - and it was under law resolution move.
I have switched to other apps (and my normal  resolution returned back) - and closed it manually.

> C:\Users\Worker>go get -u github.com/gonutz/d3d9
> 
> C:\Users\Worker>cd go
> 
> C:\Users\Worker\go>dir
>  Том в устройстве C имеет метку Win10
>  Серийный номер тома: D0F6-A093
> 
>  Содержимое папки C:\Users\Worker\go
> 
> 02.10.2020  12:14    <DIR>          .
> 02.10.2020  12:14    <DIR>          ..
> 02.10.2020  12:14    <DIR>          pkg
> 02.10.2020  12:13    <DIR>          src
>                0 файлов              0 байт
>                4 папок  10 373 697 536 байт свободно
> 
> C:\Users\Worker\go>cd src
> 
> C:\Users\Worker\go\src>dir
>  Том в устройстве C имеет метку Win10
>  Серийный номер тома: D0F6-A093
> 
>  Содержимое папки C:\Users\Worker\go\src
> 
> 02.10.2020  12:13    <DIR>          .
> 02.10.2020  12:13    <DIR>          ..
> 02.10.2020  12:13    <DIR>          github.com
>                0 файлов              0 байт
>                3 папок  10 373 697 536 байт свободно
> 
> C:\Users\Worker\go\src>cd github.com/gonutz/d3d9
> 
> C:\Users\Worker\go\src\github.com\gonutz\d3d9>dir
>  Том в устройстве C имеет метку Win10
>  Серийный номер тома: D0F6-A093
> 
>  Содержимое папки C:\Users\Worker\go\src\github.com\gonutz\d3d9
> 
> 02.10.2020  12:13    <DIR>          .
> 02.10.2020  12:13    <DIR>          ..
> 02.10.2020  12:13             6 645 base_texture_windows.go
> 02.10.2020  12:13             1 950 color_windows.go
> 02.10.2020  12:13            76 879 constants_windows.go
> 02.10.2020  12:13             8 759 cube_texture_windows.go
> 02.10.2020  12:13            54 482 device_windows.go
> 02.10.2020  12:13            10 065 direct3d9_windows.go
> 02.10.2020  12:13            99 029 enums_windows.go
> 02.10.2020  12:13             3 341 error_windows.go
> 02.10.2020  12:13             7 934 index_buffer_windows.go
> 02.10.2020  12:13             1 096 LICENSE
> 02.10.2020  12:13             1 844 macros_windows.go
> 02.10.2020  12:13             1 976 pixel_shader_windows.go
> 02.10.2020  12:13             2 458 query_windows.go
> 02.10.2020  12:13             6 964 README.md
> 02.10.2020  12:13             4 564 resource_windows.go
> 02.10.2020  12:13    <DIR>          samples
> 02.10.2020  12:13             1 818 state_block_windows.go
> 02.10.2020  12:13             7 086 surface_windows.go
> 02.10.2020  12:13             4 100 swap_chain_windows.go
> 02.10.2020  12:13             8 421 texture_windows.go
> 02.10.2020  12:13            15 379 types_windows.go
> 02.10.2020  12:13            12 020 vertex_buffer_windows.go
> 02.10.2020  12:13             2 063 vertex_declaration_windows.go
> 02.10.2020  12:13             2 002 vertex_shader_windows.go
> 02.10.2020  12:13             8 730 volume_texture_windows.go
> 02.10.2020  12:13             4 683 volume_windows.go
>               25 файлов        354 288 байт
>                3 папок  10 369 716 224 байт свободно
> 
> C:\Users\Worker\go\src\github.com\gonutz\d3d9>go build -i -v -x
> WORK=C:\Users\Worker\AppData\Local\Temp\go-build558590870
> 
> C:\Users\Worker\go\src\github.com\gonutz\d3d9>go build
> 
> C:\Users\Worker\go\src\github.com\gonutz\d3d9>go test
> ?       github.com/gonutz/d3d9  [no test files]
> 
> C:\Users\Worker\go\src\github.com\gonutz\d3d9>cd samples
> 
> C:\Users\Worker\go\src\github.com\gonutz\d3d9\samples>dir
>  Том в устройстве C имеет метку Win10
>  Серийный номер тома: D0F6-A093
> 
>  Содержимое папки C:\Users\Worker\go\src\github.com\gonutz\d3d9\samples
> 
> 02.10.2020  12:13    <DIR>          .
> 02.10.2020  12:13    <DIR>          ..
> 02.10.2020  12:13    <DIR>          display_info
> 02.10.2020  12:13    <DIR>          fullscreen
> 02.10.2020  12:13    <DIR>          rotating_quad
> 02.10.2020  12:13    <DIR>          simple_glow
> 02.10.2020  12:13    <DIR>          static_triangle
>                0 файлов              0 байт
>                7 папок  10 364 735 488 байт свободно
> 
> C:\Users\Worker\go\src\github.com\gonutz\d3d9\samples>cd fullscreen
> 
> C:\Users\Worker\go\src\github.com\gonutz\d3d9\samples\fullscreen>dir
>  Том в устройстве C имеет метку Win10
>  Серийный номер тома: D0F6-A093
> 
>  Содержимое папки C:\Users\Worker\go\src\github.com\gonutz\d3d9\samples\fullscreen
> 
> 02.10.2020  12:13    <DIR>          .
> 02.10.2020  12:13    <DIR>          ..
> 02.10.2020  12:13                31 build.bat
> 02.10.2020  12:13             2 532 main.go
> 02.10.2020  12:13               818 README.md
>                3 файлов          3 381 байт
>                2 папок  10 351 964 160 байт свободно
> 
> C:\Users\Worker\go\src\github.com\gonutz\d3d9\samples\fullscreen>build.bat
> 
> C:\Users\Worker\go\src\github.com\gonutz\d3d9\samples\fullscreen>go build -ldflags -H=windowsgui
> main.go:8:2: cannot find package "github.com/gonutz/w32" in any of:
>         c:\go\src\github.com\gonutz\w32 (from $GOROOT)
>         C:\Users\Worker\go\src\github.com\gonutz\w32 (from $GOPATH)
> 
> C:\Users\Worker\go\src\github.com\gonutz\d3d9\samples\fullscreen>go get -u github.com/gonutz/w32
> 
> C:\Users\Worker\go\src\github.com\gonutz\d3d9\samples\fullscreen>build.bat
> 
> C:\Users\Worker\go\src\github.com\gonutz\d3d9\samples\fullscreen>go build -ldflags -H=windowsgui
> 
> C:\Users\Worker\go\src\github.com\gonutz\d3d9\samples\fullscreen>dir
>  Том в устройстве C имеет метку Win10
>  Серийный номер тома: D0F6-A093
> 
>  Содержимое папки C:\Users\Worker\go\src\github.com\gonutz\d3d9\samples\fullscreen
> 
> 02.10.2020  12:17    <DIR>          .
> 02.10.2020  12:17    <DIR>          ..
> 02.10.2020  12:13                31 build.bat
> 02.10.2020  12:17         2 091 520 fullscreen.exe
> 02.10.2020  12:13             2 532 main.go
> 02.10.2020  12:13               818 README.md
>                4 файлов      2 094 901 байт
>                2 папок  10 350 559 232 байт свободно
> 
> C:\Users\Worker\go\src\github.com\gonutz\d3d9\samples\fullscreen>fullscreen.exe
>

**Comment by gonutz** [comment]
Alright, thanks for the update. In that case I will move the other examples to use the Windows API soon as well. Thanks for your contribution, I really appreciate it! :-)
