### ISSUE TITLE
cannot use flag (type uint32) as type uintptr in argument to procRedrawWindow.Call

### ISSUE THREAD

**Issue by advancedwebdeveloper** [gonutz/d3d9#7]
I wouldn't be too verbose, this time.
I have cleaned up all packages ("src", "pkg","bin) and installed your package (and all dependencies) as expected.

> C:\Users\Worker\go\src\github.com\gonutz\d3d9\samples\rotating_quad>build_all.bat
> 
> C:\Users\Worker\go\src\github.com\gonutz\d3d9\samples\rotating_quad>REM see README.md for how to use this script
> 
> C:\Users\Worker\go\src\github.com\gonutz\d3d9\samples\rotating_quad>set FXC="C:\Program Files (x86)\Windows Kits\8.1\bin\x86\fxc.exe"
> 
> C:\Users\Worker\go\src\github.com\gonutz\d3d9\samples\rotating_quad>"C:\Program Files (x86)\Windows Kits\8.1\bin\x86\fxc.exe" /WX /T vs_2_0 /Fo vs.object vs.code
> Системе не удается найти указанный путь.
> 
> C:\Users\Worker\go\src\github.com\gonutz\d3d9\samples\rotating_quad>"C:\Program Files (x86)\Windows Kits\8.1\bin\x86\fxc.exe" /WX /T ps_2_0 /Fo ps.object ps.code
> Системе не удается найти указанный путь.
> 
> C:\Users\Worker\go\src\github.com\gonutz\d3d9\samples\rotating_quad>go get github.com/gonutz/bin2go
> 
> C:\Users\Worker\go\src\github.com\gonutz\d3d9\samples\rotating_quad>bin2go -s -v vso -o vso.go vs.object
> 
> C:\Users\Worker\go\src\github.com\gonutz\d3d9\samples\rotating_quad>bin2go -s -v pso -o pso.go ps.object
> 
> C:\Users\Worker\go\src\github.com\gonutz\d3d9\samples\rotating_quad>go build -ldflags -H=windowsgui
> main.go:7:2: cannot find package "github.com/AllenDang/gform" in any of:
>         c:\go\src\github.com\AllenDang\gform (from $GOROOT)
>         C:\Users\Worker\go\src\github.com\AllenDang\gform (from $GOPATH)
> 
> C:\Users\Worker\go\src\github.com\gonutz\d3d9\samples\rotating_quad>go get -u github.com/AllenDang/gform
> # github.com/AllenDang/w32
> ..\..\..\..\AllenDang\w32\user32.go:1039:10: cannot use flag (type uint32) as type uintptr in argument to procRedrawWindow.Call

**Comment by gonutz** [comment]
Alright, I do not know why you opened this issue again, but I assume that I can close it as well then? If you encounter any other problems, just re-open this or open a new issue. Thanks again!
